apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-prediction-api
spec:
  replicas: 4  # Number of pods to run
  selector:
    matchLabels:
      app: insurance-api
  template:
    metadata:
      labels:
        app: insurance-api
    spec:
      containers:
      - name: insurance-api
        image: byberkayyildirim/insurance-prediction-api:latest  # Use your Docker Hub image
        ports:
        - containerPort: 8000